WEBAPP/Controllers/CompanyController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Office.Interop.Excel;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WEBAPP.DAL;
using WEBAPP.Models;

namespace WEBAPP.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CompanyListSearch(int[] Year)
        {
            List<Company> objCompanyList = new List<Company>();
            List<User> objUserList = new List<User>();
            objUserList = DataMapper.MapUserData(SPWrapper.GetUserList());

            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();

            if (objUser.IsAdmin)
            {
                objCompanyList = DataMapper.MapCompanyData(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList();
            }
            else
            {
                objCompanyList = DataMapper.MapCompanyData(SPWrapper.GetCompanyListByUser(Username)).Where(x => x.IsDeleted == false).ToList();
            }


            var Result = new List<Company>();


            if (Year != null)
            {
                foreach (var item in Year)
                {

                    Result.AddRange(FilterCompanyList("Year", item.ToString(), new Company()).CompanyList);
                }
            }

            return View("CompanyList", Result);
        }






        [OutputCache(Duration = 120)]
        public List<User> GetUserList()
        {
            List<User> objUserList = new List<User>();
            objUserList = DataMapper.MapUserData(SPWrapper.GetUserList());
            return objUserList;
        }



        public List<Company> FilterCompanyByUser(List<Company> objCompanyList)
        {
            List<User> objUserList = GetUserList();
            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();
            if (!objUser.IsAdmin)
            {
                objCompanyList = objCompanyList.Where(x => x.AllotedTo.ToUpper() == Username.ToUpper() && x.IsDeleted == false).ToList();
            }
            return objCompanyList;
        }
        public List<Company> GetCompanyMaster()
        {
            List<User> objUserList = new List<User>();
            List<Company> objCompanyList = new List<Company>();
            objUserList = GetUserList();
            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();
            if (objUser.IsAdmin)
            {
                objCompanyList = DataMapper.MapCompanyMaster(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList();
            }
            else
            {
                objCompanyList = DataMapper.MapCompanyMaster(SPWrapper.GetCompanyListByUser(Username)).Where(x => x.IsDeleted == false).ToList();
            }


            return objCompanyList;

        }

        public List<Company> GetCompanies()
        {
            List<User> objUserList = new List<User>();
            List<Company> objCompanyList = new List<Company>();
            objUserList = GetUserList();
            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();
            if (objUser.IsAdmin)
            {
                objCompanyList = DataMapper.MapCompanyDataForListing(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList();
            }
            else
            {
                objCompanyList = DataMapper.MapCompanyDataForListing(SPWrapper.GetCompanyListByUser(Username)).Where(x => x.IsDeleted == false).ToList();
            }


            return objCompanyList;

        }
        public List<Company> GetCompaniesForExport()
        {
            List<User> objUserList = new List<User>();
            List<Company> objCompanyList = new List<Company>();
            objUserList = GetUserList();
            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();
            if (objUser.IsAdmin)
            {
                objCompanyList = DataMapper.MapCompanyDataForExport(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList();
            }
            else
            {
                objCompanyList = DataMapper.MapCompanyDataForExport(SPWrapper.GetCompanyListByUser(Username)).Where(x => x.IsDeleted == false).ToList();
            }


            return objCompanyList;

        }


        public List<Company> GetCompaniesWithDetails()
        {
            List<User> objUserList = new List<User>();
            List<Company> objCompanyList = new List<Company>();
            objUserList = GetUserList();
            //Get Logged IN UserName
            var Username = User.Identity.GetUserName();
            // Get Logged IN User Details();
            User objUser = objUserList.Where(x => x.Email.ToUpper() == Username.ToUpper()).FirstOrDefault();
            if (objUser.IsAdmin)
            {
                objCompanyList = DataMapper.MapCompanyData(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList();
            }
            else
            {
                objCompanyList = DataMapper.MapCompanyData(SPWrapper.GetCompanyListByUser(Username)).Where(x => x.IsDeleted == false).ToList();
            }

            return objCompanyList;
        }


        [HttpGet]
        public ActionResult CompanyList()

        {
            Company objCompany = new Company();
            objCompany = GetCommonData(objCompany);
            objCompany.CompanyList = GetCompanyMaster();
            return View(objCompany);
        }

        [HttpGet]
        public ActionResult CompanyListv2()

        {
            Company objCompany = new Company();
            objCompany = GetCommonData(objCompany);
            objCompany.CompanyList = GetCompanyMaster();
            return View(objCompany);
        }

        [HttpPost]
        public JsonResult GetDetails()
        {

            List<Company> data = new List<Company>();
            var start = (Convert.ToInt32(Request["start"]));
            var Length = (Convert.ToInt32(Request["length"])) == 0 ? 10 : (Convert.ToInt32(Request["length"]));
            var searchvalue = Request["search[value]"] ?? "";
            var sortcoloumnIndex = Convert.ToInt32(Request["order[0][column]"]);
            var SortColumn = "";
            var SortOrder = "";
            var sortDirection = Request["order[0][dir]"] ?? "asc";
            var recordsTotal = 0;
            var username = User.Identity.GetUserName().ToUpperInvariant() == "ADMIN@AE.IN" ? "" : User.Identity.GetUserName();

            try
            {
                switch (sortcoloumnIndex)
                {
                    case 0:
                        SortColumn = "CompanyName";
                        break;
                    case 1:
                        SortColumn = "CreatedOn ";
                        break;
                    case 2:
                        SortColumn = "DateGiven";
                        break;

                    default:
                        SortColumn = "AllotedTo";
                        break;
                }
                if (sortDirection == "asc")
                    SortOrder = "asc";
                else
                    SortOrder = "desc";
                data = GetCompanies(start, searchvalue, Length, SortColumn, sortDirection, username).ToList();
                recordsTotal = data.Count > 0 ? data.Count : 0;
            }
            catch (Exception ex)
            {
            }
            return Json(new { data = data, recordsTotal = recordsTotal, recordsFiltered = recordsTotal }, JsonRequestBehavior.AllowGet);
        }



        public List<Company> GetCompanies(int start, string searchvalue, int length, string sortColumn, string sortDirection, string username)
        {
            return DataMapper.MapCompanyDataForListing(SPWrapper.GetCompanyListByPage(start, searchvalue, length, sortColumn, sortDirection, username)).Where(x => x.IsDeleted == false).ToList();
        }

        [HttpGet]
        public ActionResult Export()

        {
            Company objCompany = new Company();
            objCompany = GetCommonData(objCompany);
            objCompany.CompanyList = GetCompaniesForExport();
            return View(objCompany);
        }

        [HttpPost]

WEBAPP/Views/Company/AddCourse.cshtml
@model WEBAPP.Models.Course

@{
    ViewBag.Title = "AddCourse";
}

<h2>AddCourse</h2>

@using (Html.BeginForm("SaveCourse","Company")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-sm btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CourseList","Company",new {@class="btn btn-sm btn-success" })
</div>

WEBAPP/Views/Company/AddStream.cshtml
@model WEBAPP.Models.Stream

@{
    ViewBag.Title = "AddStream";
}

<h2>AddStream</h2>

<script>

    function getStreaM(Id) {

        $.ajax({
            url: "/Company/getStream",
            data: { 'Id': Id },
            success: function (data) {

                $("#Id").val(data.Id);
                $("#Name").val(data.Name);
                $("#Description").val(data.Description);

            }
        });
    }

</script>


@using (Html.BeginForm("SaveStream","Company")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
         
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CourseId, new SelectList(Model.CourseDrp, "CourseName", "CourseName"), "  Select   ")
                @*@Html.DropDownListFor(model => model.CourseId, Model.CourseDrp, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-sm btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "StreamList","",new {@class="btn btn-sm btn-success" })
</div>

WEBAPP/Views/Company/CityList.cshtml
@model IEnumerable<WEBAPP.Models.CityMaster>
@using WEBAPP.DAL;

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<script>

    function getCity(Id) {

        $.ajax({
            url: "/Company/getCity",
            data: { 'Id': Id },
            success: function (data) {

                $("#Id").val(data.Id);
                $("#City").val(data.City);


            }
        });
    }

</script>

@using (Html.BeginForm("SaveCity", "Company", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form", role = "form" }))
{


    <div class="row">
        <div class="col-3">

            <input type="text" required class="form-control text-box" placeholder="City" id="City" name="City" />
            <input type="hidden" name="Id" id="Id" />
            @*<input type="hidden" name="Type" id="Type" />*@
        </div>
        @*<div class="col-3">

                <input type="text" required class="form-control text-box" placeholder="Description" id="Description" name="Description" />

            </div>*@
        <div>
            <input type="submit" class="btn btn-sm btn-primary" value="Save City" />
        </div>

    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>

            <td>
                <a onclick="getCity(`@item.Id`);"> <span class="fas fa-edit">edit</span></a>
            </td>
        </tr>
    }

</table>

WEBAPP/Views/Company/ColorMaster.cshtml
@model IEnumerable<WEBAPP.Models.Master>

@{
    ViewBag.Title = "ColorMaster";
}

<script>

    function getColorMaster(Id) {

        $.ajax({
            url: "/Company/getColorMaster",
            data: { 'Id': Id },
            success: function (data) {

                $("#Id").val(data.Id);
                $("#Name").val(data.Name);
                $("#Description").val(data.Description);

            }
        });
    }

</script>

<h2>Color <i class="fas fa-palette"></i></h2>

@using (Html.BeginForm("ColorMaster", "Company", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form", role = "form" }))
{


<div class="row">
    <div class="col-3">
        <input type="text" required class="form-control text-box" placeholder="Color" id="Name" name="Name" />       
        <input type="hidden" name="Id" id="Id" />
        <input type="hidden" name="Type" id="Type" />
    </div>
    <div class="col-3">
       
        <input type="text" required class="form-control text-box" placeholder="Description" id="Description" name="Description" />
        
    </div>
    <div>
        <input type="submit" class="btn btn-sm btn-primary" value="Save Color" />
    </div>

</div>
}
<br />
<table class="table table-striped">
    <tr>
        <th>

            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i +1 }))
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Data.Id)
    </td>
    <td>
        <button type="button" style="background-color:@item.Data.Name" class="btn btn-sm"></button>
        @Html.DisplayFor(modelItem => item.Data.Name)
    </td>
    <td>
      
        @Html.DisplayFor(modelItem => item.Data.Description)
    </td>
    <td>
        <a onclick="getColorMaster(`@item.Data.Id`);"> <span class="fas fa-edit">edit</span></a>
    </td>
</tr>
    }

</table>

WEBAPP/Views/Company/CourseList.cshtml
@model IEnumerable<WEBAPP.Models.Course>

@{
    ViewBag.Title = "CourseList";
}

<h2>CourseList</h2>

<p>
    @Html.ActionLink("Create New", "AddCourse","Company",new {@class="btn btn-sm btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </th>*@
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CourseName)
    </td>
    @*<td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedBy)
        </td>*@
    <td>
        @Html.ActionLink("Edit", "EditCourse", new { id=item.Id }) 
          
    </td>
</tr>
}

</table>

WEBAPP/Views/Company/EditStream.cshtml
@model WEBAPP.Models.Stream

@{
    ViewBag.Title = "Edit Cou";
}

<h2>Edit Stream</h2>

<script>

    function getStreaM(Id) {

        $.ajax({
            url: "/Company/getStream",
            data: { 'Id': Id },
            success: function (data) {

                $("#Id").val(data.Id);
                $("#Name").val(data.Name);
                $("#Description").val(data.Description);

            }
        });
    }

</script>


@using (Html.BeginForm("SaveStream","Company")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
         
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id);
        <div class="form-group">
            @Html.Label("Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CourseId, new SelectList(Model.CourseDrp, "CourseName", "CourseName"), "  Select   ")
                @*@Html.DropDownListFor(model => model.CourseId, Model.CourseDrp, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-sm btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "StreamList","",new {@class="btn btn-sm btn-success" })
</div>

WEBAPP/Views/Company/SectorMaster.cshtml
@model IEnumerable<WEBAPP.Models.Master>

@{
    ViewBag.Title = "SectorMaster";
}

<h2>Sector Master</h2>

<script>

    function getSectorMaster(Id) {

        $.ajax({
            url: "/Company/getSectorMaster",
            data: { 'Id': Id },
            success: function (data) {

                $("#Id").val(data.Id);
                $("#Name").val(data.Name);
              

            }
        });
    }

</script>

@using (Html.BeginForm("SectorMaster", "Company", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form", role = "form" }))
{

    <div class="row">
        <div class="col-3">
            <input type="text" required class="form-control text-box" placeholder="Sector" id="Name" name="Name" />
            <input type="hidden" name="Id" id="Id" />
            <input type="hidden" name="Type" id="Type" />
        </div>
        
        <div>
            <input type="submit" class="btn btn-sm btn-primary" value="Save Sector" />
        </div>

    </div>
    
   
}
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        
        <th>Action</th>
    </tr>

    @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i +1 }))
    {
        <tr>
            <td>
                @item.Index
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data.Name)
            </td>
            <td>
                <a onclick="getSectorMaster(`@item.Data.Id`);">Edit</a>
            </td>
        </tr>
    }

</table>

WEBAPP/Views/Company/StreamList.cshtml
@model IEnumerable<WEBAPP.Models.Stream>

@{
    ViewBag.Title = "StreamList";
}

<h2>StreamList</h2>

<p>
    @Html.ActionLink("Create New", "AddStream","",new {@class="btn btn-sm btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StreamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
     
       
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StreamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
 
        <td>
            @Html.ActionLink("Edit", "EditStream", new { id=item.Id },new {@class="btn btn-sm btn-success" }) 
            @*@Html.ActionLink("Details", "Details", new { id=item.Id },new {@class="btn btn-sm btn-success" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id },new {@class="btn btn-sm btn-success" })*@
        </td>
    </tr>
}

</table>

WEBAPP/Views/Company/ThirdPartyList.cshtml
@model IEnumerable<WEBAPP.Models.ThirdParty>

@{
    ViewBag.Title = "ThirdPartyList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Third Party List</h2>

<p>
    @Html.ActionLink("Create New", "AddThirdParty", "Company", new { @class = "btn btn-sm btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditThirdParty", new { id = item.Id }, new { @class = "btn btn-sm btn-success" })
            @*|@Html.ActionLink("Details", "Details", new { id=item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
        </td>
    </tr>
}

</table>