WEBAPP/Models/Payroll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBAPP.Models
{
    public class Payroll
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public int DesignationId { get; set; }
        public decimal WorkingDays { get; set; }
        public decimal LeaveDays { get; set; }
        public decimal OvertimeDays { get; set; }
        public decimal PaidLeaveDays { get; set; }
        public decimal TotalWorkingDays { get; set; }
        public decimal SalaryAmount { get; set; }
        public decimal GrossSalaryAmount { get; set; }
        public decimal DeductionAmount { get; set; }
        public string DeductionDetails { get; set; }
        public decimal IncentiveAmount { get; set; }
        public decimal AdvancePaidAmount { get; set; }
        public decimal AdvanceDeductedAmount { get; set; }
        public decimal AdditionalPaidAmount { get; set; }
        public decimal AdditionalDeductedAmount { get; set; }
        public string AdditionalPaidDetails { get; set; }
        public string AdditionalDeductedDetails { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal NetSalaryAmount { get; set; }
        
        public DateTime CreatedOn { get; set; }
        public DateTime UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public SelectList DDLUser { get; set; }
        public SelectList DDLCompany { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeName { get; set; }
    }
}

WEBAPP/Controllers/PayrollController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Office.Interop.Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEBAPP.DAL;
using WEBAPP.Models;

namespace WEBAPP.Controllers
{
    public class PayrollController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Payroll
        public ActionResult Index()
        {
            return View(DataMapper.MapPayrollData(SPWrapper.GetPayrollData()));
        }

        // GET: Payroll/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payroll payroll = DataMapper.MapPayrollData(SPWrapper.GetPayrollData()).Find(m => m.Id == id);

            if (payroll == null)
            {
                return HttpNotFound();
            }
            return View(payroll);
        }

        // GET: Payroll/Create
        public ActionResult Create()
        {
            Payroll payroll = new Payroll();
            var Username = User.Identity.GetUserName();
            payroll.DDLCompany = new SelectList(DataMapper.MapCompanyData(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList(), "Id", "CompanyName");
            payroll.DDLUser = new SelectList(DataMapper.MapUserData(SPWrapper.GetUserList()), "Id", "FirstName");
            return View(payroll);
        }

        // POST: Payroll/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EmployeeId,CompanyId,DesignationId,WorkingDays,LeaveDays,OvertimeDays,PaidLeaveDays,TotalWorkingDays,SalaryAmount,GrossSalaryAmount,DeductionAmount,DeductionDetails,IncentiveAmount,AdvancePaidAmount,AdvanceDeductedAmount,AdditionalPaidAmount,AdditionalDeductedAmount,AdditionalPaidDetails,AdditionalDeductedDetails,Month,Year,NetSalaryAmount,CreatedOn,UpdatedOn,CreatedBy,UpdatedBy")] Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                SPWrapper.AddPayroll(payroll);

                return RedirectToAction("Index");
            }

            return View(payroll);
        }

        // GET: Payroll/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payroll payroll = DataMapper.MapPayrollData(SPWrapper.GetPayrollData()).Find(m => m.Id == id);
            var Username = User.Identity.GetUserName();
            payroll.DDLCompany = new SelectList(DataMapper.MapCompanyData(SPWrapper.GetCompanyList()).Where(x => x.IsDeleted == false).ToList(), "Id", "CompanyName");
            payroll.DDLUser = new SelectList(DataMapper.MapUserData(SPWrapper.GetUserList()), "Id", "FirstName");
            if (payroll == null)
            {
                return HttpNotFound();
            }
            return View(payroll);
        }

        // POST: Payroll/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployeeId,CompanyId,DesignationId,WorkingDays,LeaveDays,OvertimeDays,PaidLeaveDays,TotalWorkingDays,SalaryAmount,GrossSalaryAmount,DeductionAmount,DeductionDetails,IncentiveAmount,AdvancePaidAmount,AdvanceDeductedAmount,AdditionalPaidAmount,AdditionalDeductedAmount,AdditionalPaidDetails,AdditionalDeductedDetails,Month,Year,NetSalaryAmount,CreatedOn,UpdatedOn,CreatedBy,UpdatedBy")] Payroll payroll)
        {
            if (ModelState.IsValid)
            {
                SPWrapper.UpdatePayroll(payroll);
                return RedirectToAction("Index");
            }
            return View(payroll);
        }

        // GET: Payroll/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payroll payroll = DataMapper.MapPayrollData(SPWrapper.GetPayrollData()).Find(m => m.Id == id);

            if (payroll == null)
            {
                return HttpNotFound();
            }
            return View(payroll);
        }

        // POST: Payroll/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payroll payroll = db.Payrolls.Find(id);
            db.Payrolls.Remove(payroll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WEBAPP/Views/Payroll/AddPayroll.cshtml
@model WEBAPP.Models.Payroll
@{
    /**/

    ViewBag.Title = "";
}

@*<h2>@ViewBag.Title.</h2>*@

@using (Html.BeginForm("AddPayroll", "Payroll", FormMethod.Post, new { @class = "w-75 container", role = "form" }))
{
    @Html.AntiForgeryToken()

    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })
    <style>

        /*.row {
            border-style: groove;
        }*/

    </style>
    <div class="form-group">

        <label class="d-flex justify-content-center"><b>Immigration security services pvt ltd</b></label>
        <label class="d-flex justify-content-center"><b>A-39, Ring Rd, Awas Vikas, Rudrapur, Jagatpura, Uttarakhand 263153</b></label>
        <p></p>
    </div>
    @*<div class="form-group">

        </div>*@

    <div class="form-group">

        <label class="d-flex justify-content-center"><b>Pay Slip: Mar-24</b></label>
    </div>
    <br />
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Employee Name</label>
            <div class="col-sm-3">

                @Html.TextBoxFor(m => m.EmployeeId, new { @class = "form-control", @required = "required", @autocomplete = "off" })


            </div>
            <label class="col-sm-3">Company Name</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.CompanyId, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Designation</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DesignationId, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Leave Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.LeaveDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Overtime Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.OvertimeDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Paid Leave Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.PaidLeaveDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Total Working Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.TotalWorkingDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.SalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Gross Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.GrossSalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Deduction Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DeductionAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Deduction Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DeductionDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Incentive Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.IncentiveAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-6 d-flex justify-content-center"><b>Earings</b></label>

            <label class="col-sm-6 d-flex justify-content-center"><b>Deductions</b></label>

        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Advance Paid Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdvancePaidAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Advance Deducted Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdvanceDeductedAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Additional Paid Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalPaidAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Additional Deducted Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalDeductedAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Additional Paid Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalPaidDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Additional Deducted Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalDeductedDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Month</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Month, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Year</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Year, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Net Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.NetSalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Working Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.WorkingDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>









}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WEBAPP/Views/Payroll/Delete.cshtml
@model WEBAPP.Models.Payroll

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Payroll</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.EmployeeId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EmployeeId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CompanyId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CompanyId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DesignationId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DesignationId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.WorkingDays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.WorkingDays)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.LeaveDays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.LeaveDays)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.OvertimeDays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.OvertimeDays)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PaidLeaveDays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PaidLeaveDays)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TotalWorkingDays)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TotalWorkingDays)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SalaryAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SalaryAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.GrossSalaryAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.GrossSalaryAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DeductionAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DeductionAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DeductionDetails)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DeductionDetails)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IncentiveAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IncentiveAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdvancePaidAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdvancePaidAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdvanceDeductedAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdvanceDeductedAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdditionalPaidAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdditionalPaidAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdditionalDeductedAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdditionalDeductedAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdditionalPaidDetails)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdditionalPaidDetails)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdditionalDeductedDetails)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdditionalDeductedDetails)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Month)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Month)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Year)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Year)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.NetSalaryAmount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.NetSalaryAmount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UpdatedBy)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

WEBAPP/Views/Payroll/UpdatePayroll.cshtml
@model WEBAPP.Models.Payroll
@{
    /**/

    ViewBag.Title = "";
}

@*<h2>@ViewBag.Title.</h2>*@

@using (Html.BeginForm("UpdatePayroll", "Payroll", FormMethod.Post, new { @class = "w-75 container", role = "form" }))
{
    @Html.AntiForgeryToken()

    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })
    <style>

        /*.row {
            border-style: groove;
        }*/

    </style>
    <div class="form-group">

        <label class="d-flex justify-content-center"><b>Immigration security services pvt ltd</b></label>
        <label class="d-flex justify-content-center"><b>A-39, Ring Rd, Awas Vikas, Rudrapur, Jagatpura, Uttarakhand 263153</b></label>
        <p></p>
    </div>
    @*<div class="form-group">

        </div>*@

    <div class="form-group">

        <label class="d-flex justify-content-center"><b>Pay Slip: Mar-24</b></label>
    </div>
    <br />
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Employee Name</label>
            <div class="col-sm-3">

                @Html.TextBoxFor(m => m.EmployeeId, new { @class = "form-control", @required = "required", @autocomplete = "off" })


            </div>
            <label class="col-sm-3">Company Name</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.CompanyId, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Designation</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DesignationId, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Leave Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.LeaveDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Overtime Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.OvertimeDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Paid Leave Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.PaidLeaveDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Total Working Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.TotalWorkingDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.SalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Gross Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.GrossSalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Deduction Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DeductionAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Deduction Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.DeductionDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Incentive Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.IncentiveAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-6 d-flex justify-content-center"><b>Earings</b></label>

            <label class="col-sm-6 d-flex justify-content-center"><b>Deductions</b></label>

        </div>

    </div>

    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Advance Paid Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdvancePaidAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Advance Deducted Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdvanceDeductedAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Additional Paid Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalPaidAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Additional Deducted Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalDeductedAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Additional Paid Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalPaidDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Additional Deducted Details</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.AdditionalDeductedDetails, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Month</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Month, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Year</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.Year, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <label class="col-sm-3">Net Salary Amount</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.NetSalaryAmount, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
            <label class="col-sm-3">Working Days</label>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.WorkingDays, new { @class = "form-control", @required = "required", @autocomplete = "off" })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>









}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}